### PR TITLE
Removed recaptcha_ajax.js as google deprecated it

### LINKED ISSUE #2: No longer required recaptcha_ajax.js
It seems the recaptcha_ajax.js is no longer required and removed by Google, can you remove `Requirements::javascript('https://www.google.com/recaptcha/api/js/recaptcha_ajax.js');` 
from CyberDuck\Recaptcha\Forms\RecaptchaField, as it is throwing a javascript error for 404 not found and MIME type miss match?

### PR DESCRIPTION
**Pull request by n8-dev**
Resolves #2

### CODE REVIEW

**Comment by n8-dev** [comment]
@Andrew-Mc-Cormack 

Any chance this could get merged in?

**Comment by n8-dev** [comment]
Or perhaps @samthejarvis you could help?

Many thanks :D

**Comment by gligorkot** [comment]
Resolves #4 as well now

**Comment by samthejarvis** [comment]
Looks good here - thank you both!

**Comment by n8-dev** [comment]
👏 many thanks @samthejarvis 🎉 

You may want to tweak the release note to mention support for guzzle 7 / ss4.11 is loosely available now.

**Comment by gligorkot** [comment]
🚀

**Pull request merged**
